export let ShopByCategory = [{ name: "Fruits", link: "fruits", image: "../../assets/images/fruits_2.jpg" },
{ name: "Daily Vegetables", link: "dailyvegetables", image: "../../assets/images/cabbage_veggie_2.jpg" },
{ name: "Exotic Vegetables", link: "exoticvegetables", image: "../../assets/images/bellpepper.jpg" },
{ name: "Herbs and Seasoning", link: "herbsandseasoning", image: "../../assets/images/herbsandseasoning_2.jpg" },
{ name: "Organic", link: "organic", image: "../../assets/images/organic_2.jpg" },
{ name: "Exotic", link: "exotic", image: "../../assets/images/kiwi.jpg" }]

export let DailyEssesntial = [{name: "Onions, Potatoes and Tomatoes", link: "Onions Potatoes Tomatoes", image:"../../assets/images/opt.jpg"},
{name: "Chillies, Garlic, Lemon and Ginger", link: "Chillies Garlic Lemon Ginger", image:"../../assets/images/cglg.jpg"},
{name: "Apple, Banana and Pear", link: "Apple Banana Pear", image:"../../assets/images/abp.jpg"},
{name: "Mangoes", link: "Mangoes", image:"../../assets/images/fruits.jpg"},
{name: "Citrus Fruits", link: "Citrus Fruits", image:"../../assets/images/oranges.jpg"},
{name: "Berries", link: "Berries", image:"../../assets/images/fruits_2.jpg"},
{name: "Broccoli, Cabbage and Cauliflower", link: "Broccoli Cabbage Cauliflower", image:"../../assets/images/bcc.jpg"},
{name: "Lemon, Ginger and Garlic", link: "Lemon Ginger Garlic", image:"../../assets/images/lgg.jpg"},
{name: "Cucumber and Capsicum", link: "Cucumber Capsicum", image:"../../assets/images/cucap.jpg"},
{name: "Organic Vegetables", link: "Exotic Vegetables", image:"../../assets/images/orveg.jpeg"}]

export let FamousInYourArea = [{name: "Alphanso Mangoes", link: "6049cee450b5b0ceecba6d99", image:"../../assets/images/alphonso.jpg"},
{name: "Strawberry", link: "6049cee450b5b0ceecba6dae", image:"../../assets/images/strawberry.jpg"},
{name: "Watermelon", link: "60895e3c1bc9421a548c0ce7", image:"../../assets/images/watermelon.jpg"},
{name: "Broccoli", link: "60701721298c9d2098fc3151", image:"../../assets/images/fruits.jpg"},
{name: "Red Capsicum", link: "6049cee450b5b0ceecba6da9", image:"../../assets/images/redcap.jpg"},
{name: "Onions", link: "6049cee550b5b0ceecba6dc8", image:"../../assets/images/onions.jpg"},
{name: "Tomatoes", link: "6049cee550b5b0ceecba6dcb", image:"../../assets/images/tomatoes.jpg"},
{name: "Spring Onions", link: "6087decef3b41305d0350b6e", image:"../../assets/images/springonion.jpg"},
{name: "Ginger", link: "60895ed21bc9421a548c0ceb", image:"../../assets/images/ginger.jpg"},
{name: "Lemon", link: "6049cee450b5b0ceecba6d93", image:"../../assets/images/lemons.jpeg"}]

export let Explore =[{name: "Kiwi", link: "608938475f40203d6c9a2019", image:"../../assets/images/kiwinew.jpg"},
{name: "Spring Onions", link: "6087decef3b41305d0350b6e", image:"../../assets/images/springonion.jpg"},
{name: "Sunmelon", link: "6089655e1bc9421a548c0d0a", image:"../../assets/images/sunmelon.jpg"},
{name: "Asparagus", link: "6049cee350b5b0ceecba6d85", image:"../../assets/images/asparagus.jpg"},
{name: "Brinjal", link: "6049cee350b5b0ceecba6d8a", image:"../../assets/images/brinjal.jpg"},
{name: "Zucchini", link: "608965e41bc9421a548c0d0f", image:"../../assets/images/zucchini.jpeg"},
{name: "Artichoke", link: "608960e51bc9421a548c0cf5", image:"../../assets/images/artichoke.jpg"},
{name: "Fennel", link: "608963c81bc9421a548c0cfa", image:"../../assets/images/fennel.jpg"},
{name: "Leek", link: "6089641e1bc9421a548c0cff", image:"../../assets/images/leek.jpg"},
{name: "Celery", link: "608964761bc9421a548c0d04", image:"../../assets/images/celery.jpeg"}]

export let YouRecentlyPurchased =[{name: "Celery", link: "608964761bc9421a548c0d04", image:"../../assets/images/celery.jpeg"},
{name: "Onions", link: "6049cee550b5b0ceecba6dc8", image:"../../assets/images/onions.jpg"},
{name: "Spring Onions", link: "6087decef3b41305d0350b6e", image:"../../assets/images/springonion.jpg"},
{name: "Kiwi", link: "608938475f40203d6c9a2019", image:"../../assets/images/kiwinew.jpg"},
{name: "Alphanso Mangoes", link: "6049cee450b5b0ceecba6d99", image:"../../assets/images/alphonso.jpg"},
{name: "Red Capsicum", link: "6049cee450b5b0ceecba6da9", image:"../../assets/images/redcap.jpg"},
{name: "Broccoli", link: "60701721298c9d2098fc3151", image:"../../assets/images/fruits.jpg"},
{name: "Asparagus", link: "6049cee350b5b0ceecba6d85", image:"../../assets/images/asparagus.jpg"},
{name: "Strawberry", link: "6049cee450b5b0ceecba6dae", image:"../../assets/images/strawberry.jpg"},
{name: "Ginger", link: "60895ed21bc9421a548c0ceb", image:"../../assets/images/ginger.jpg"},
{name: "Garlic", link: "608960661bc9421a548c0cf0", image:"../../assets/images/garlic.jpg"},
]