export let AllUrls = {
   
        'state': "http://localhost:5001/v1/location/states",
        'district': "http://localhost:5001/v1/location/states/districts",
        'address': "http://localhost:5001/v1/users/address",
        'cart': "http://localhost:5001/v1/consumer/cart",
        'item': "http://localhost:5001/v1/products/categories/items/item",
        'items': "http://localhost:5001/v1/products/categories/items/items",
        'cartitem': "http://localhost:5001/v1/consumer/cart/item",
       'emailver': "http://localhost:5001/v1/users/enableUser",
        'filter': 'http://localhost:5001/v1/products/categories/items/filteritems',
        'forgotpswrd' : "http://localhost:5001/v1/emailservice",
        'profile': "http://localhost:5001/v1/users/profile",
        'loginurl' : "http://localhost:5001/v1/users/login",
        "orders": "http://localhost:5001/v1/consumer/orders",
        "ongoingorder": "http://localhost:5001/v1/consumer/order",
        "pickup": "http://localhost:5001/v1/logistics/pickup",
        'register' : "http://localhost:5001/v1/users/registration",
        'resetpswrd' : "http://localhost:5001/v1/users/changepassword",
        "shipment": "http://localhost:5001/v1/farmers/farmer/shipments",
        "product": "http://localhost:5001/v1/products/product",
        "weather": "https://api.openweathermap.org/data/2.5/weather?q=mumbai&appid=26e5328b110058f21b8e2cf2969ea645",
        'comment': "http://localhost:5001/v1/products/product/comment",
        "bid": "http://localhost:5001/v1/products/product/bid",
        "acceptbid": "http://localhost:5001/v1/farmers/farmer/bid",
    }