export let AllUrls = {
   
        'state': "https://temp-name-1.herokuapp.com/v1/location/states",
        'district': "https://temp-name-1.herokuapp.com/v1/location/states/districts",
        'address': "https://temp-name-1.herokuapp.com/v1/users/address",
        'cart': "https://temp-name-1.herokuapp.com/v1/consumer/cart",
        'item': "https://temp-name-1.herokuapp.com/v1/products/categories/items/item",
        'items': "https://temp-name-1.herokuapp.com/v1/products/categories/items/items",
        'cartitem': "https://temp-name-1.herokuapp.com/v1/consumer/cart/item",
       'emailver': "https://temp-name-1.herokuapp.com/v1/users/enableUser",
        'filter': 'https://temp-name-1.herokuapp.com/v1/products/categories/items/filteritems',
        'forgotpswrd' : "https://temp-name-1.herokuapp.com/v1/emailservice",
        'profile': "https://temp-name-1.herokuapp.com/v1/users/profile",
        'loginurl' : "https://temp-name-1.herokuapp.com/v1/users/login",
        "orders": "https://temp-name-1.herokuapp.com/v1/consumer/orders",
        "ongoingorder": "https://temp-name-1.herokuapp.com/v1/consumer/order",
        "pickup": "https://temp-name-1.herokuapp.com/v1/logistics/pickup",
        'register' : "https://temp-name-1.herokuapp.com/v1/users/registration",
        'resetpswrd' : "https://temp-name-1.herokuapp.com/v1/users/changepassword",
        "shipment": "https://temp-name-1.herokuapp.com/v1/farmers/farmer/shipments",
        "product": "https://temp-name-1.herokuapp.com/v1/products/product",
        "weather": "https://api.openweathermap.org/data/2.5/weather?q=mumbai&appid=26e5328b110058f21b8e2cf2969ea645",
        'comment': "https://temp-name-1.herokuapp.com/v1/products/product/comment",
        "bid": "https://temp-name-1.herokuapp.com/v1/products/product/bid",
        "acceptbid": "https://temp-name-1.herokuapp.com/v1/farmers/farmer/bid",
    }